spotbugs/spotbugs-maven-plugin

src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy

Fixed a bug regarding AuxClasspath path separation

---

README.md

Updated the spotbugs-maven-plugin version to 3.1.1 instead of a SNAPSHOT to resolve #24.

#24 Updated the spotbugs-maven-plugin version

---

.travis.yml
pom.xml

Note: 2 integration tests fail with jdk 10 and will need a closer look before releasing this set.

Update base parent, doxia tools, and add jdk 10 build support

---

src/main/groovy/org/codehaus/mojo/spotbugs/SpotbugsViolationCheckMojo.groovy

[enhance] spotbugs:check use error output for maven color encoding

---

.travis.yml
pom.xml

jdk10 support and aligning version back to spotbugs for clarity.

Released 3.1.3.1

---

src/main/groovy/org/codehaus/mojo/spotbugs/SpotbugsViolationCheckMojo.groovy

added maxAllowedViolations property similar to CheckStyle to ignore the N number of errors where N is value of the property maxAllowedViolations.
refer - #84

added maxAllowedViolations property similar to checkstyle.

---

.mvn/jvm.config

TieredCompilation
TieredStopAtLevel 1

[mvn] Add jvm config for faster compilations

---

.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd
pom.xml

Update spotbugs to 3.1.12 and many other dependencies to newer versions

---

pom.xml

This was missed on last release.  In order to not confuse users, noting that PR 111 is not included even though it came in just before these 2 commits.

Merge in release of 3.1.12 (note that pr 111 is not included in 3.1.12)

---

src/it/no-src/src/test/java/EmptyJUnitTest.java
src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsGui.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsInfo.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/SpotbugsReportGenerator.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/SpotbugsViolationCheckMojo.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/XDocsReporter.groovy

git can be used for this and the files have changed far too much since originally being written to have one single owner.

[ci] More open source friendly, removing author tags in source files

---

pom.xml

[pom] Use jcl-over-slf4j instead of obsolete commons-logging

---

src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy

This project requires maven 3.2.5.  The error in question and related fix is from 2005.

[cleanup] Remove maven 2.2.1 related issue

---

.github/workflows/ci.yaml
.github/workflows/coveralls.yaml
.github/workflows/coverity.yaml
.github/workflows/it.yaml
.github/workflows/site.yaml
.github/workflows/sonar.yaml
.github/workflows/sonatype.yaml

https://github.com/actions/setup-java/blob/main/README.md

[actions] setup-java v2

---

src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy

[alignment] Update deprecated output argument for spotbugs 4.5.x

---

pom.xml

was not picking up from my base parent.

[pom] Add myself to developers / contributor section

---

src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy

split setup throughout so it is possible to run both now.

[reports] Support running reports for xml and sarif

---

pom.xml

fixes recursive issue affecting m2e (ie eclipse).

[pom] Bump base-parent to 38

---

README.md
pom.xml

waiting on groovy before release so we have java 23 support.

Preparing for 4.8.4.0 release

---

pom.xml

note ready yet for doxia upgrade

[pom] Move site back to 3.12.1

---

.mvn/jvm.config

running site needed this on java 22.  Its been working otherwise so probably some new issue on legacy doxia 1.  Adding it to overcome issue.

Add add opens for java.lang and java.util

---

src/it/sarif-1/verify.groovy
src/it/sarif-2/verify.groovy

Have not typed the variables but its far better tan using def needlessly

[tests] Make sarif not use 'def'

---

README.md

Documentation update including how to override spotbugs

---

pom.xml

does not handle traits
does not handle non packages groovy scripts

[pom] Exclude groovy files that open rewrite does not handle currently

---

pom.xml
src/stubfixer/java/com/github/spotbugs/StubOverrideFixer.java

formatting was also missed there as it did not handle auto generated code held off for creation during test phase, so run that secondary one to resolve.

Adjustments to handle auto generated groovy code on test path as well

---

README.md
pom.xml
src/site/apt/index.apt.vm

Site and build updates

---

.github/workflows/it-maven-3.6.3.yaml
.github/workflows/it-maven-4.0.0.yaml
.github/workflows/it.yaml
src/it/sarif-2/pom.xml
src/it/sarif-2/verify.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/ResourceHelper.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/SourceFileIndexer.groovy
src/test/groovy/org/codehaus/mojo/spotbugs/SourceFileIndexerTest.groovy

multiple issues, sarif items were 4 tics but that is incorrect.  New logic in normalization followed that and still incorrect.  Corrected so this is accurate.  on windows, it was failing for sarif but now working.  Due to that set 2 of the 3 integration tests to the platforms not exercised to ensure we get more coverage.

Cleanup normalization for windows

---

src/main/groovy/org/codehaus/mojo/spotbugs/BaseViolationCheckMojo.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/ResourceHelper.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/SourceFileIndexer.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/SpotbugsReportGenerator.groovy
src/main/groovy/org/codehaus/mojo/spotbugs/XDocsReporter.groovy

SonarLint is complaining about some small issues in the project. This PR fixes some of them. None of them changes the functionality, it's only a small cleanup.

small cleanup
