- .travis.yml
Currently our manual has no page which explains usage of spotbugs-maven-plugin.
So I'm going to make it by https://github.com/spotbugs/spotbugs/pull/396, but Maven can generate enough site to tell usage so I want to link from manual site.
This PR will let us push maven site from `spotbugs` branch to GitHub pages.
Before you merge this PR, make sure that @spotbugs-bot can push changes to this repository.
I think that you need to add her to member of this repository.
> Deploy Maven site to gh-page

- .travis.yml
- src/it-tools/build-tools/src/main/resources/filters/lib-filter2.xml
- src/it-tools/build-tools/src/main/resources/whizbang/lib-filter.xml
- src/it/MFINDBUGS-145/src/main/java/org/codehaus/mojo/findbugsmavenplugin/it/mfindbugs145/App.java
- src/it/MFINDBUGS-145/verify.bsh
- src/it/common.xml
- src/it/exclude-modules/module1/src/main/excludeBugs.xml
- src/main/groovy/org/codehaus/mojo/findbugs/FindbugsReportGenerator.groovy
- src/main/groovy/org/codehaus/mojo/findbugs/XDocsReporter.groovy
This project supports integration test, then enable it in Travis build. This PR also fixes several problems in maven-spotbugs-plugin:
- 34568bf41e51afdc4058fbc6c42e1843c3dc4361: support multiple `<Class>` in the same `<BugInstance>`, to generate correct xdoc report (which made many integration test failed)
- ba4ed4af2ac261837f20db38a71e923c7757d099: revert over replacement to generate HTML report (which made MFINDBUGS-145 failed)
> Revive integration test

- .travis.yml
- pom.xml
All of this in theory should work.  It does on my local windows 10 machine.  However, seems like travis is doing something different some way or another that is causing numerous java 9 issues to surface.
- Added oracle jdk9
- Updated groovy to latest 2.4.13
- Updated maven to 3.5.2
- Updated javadoc plugin to 3.0.0
- Updated enforcer plugin to 3.0.0-M1
- Updated compiler plugin to 3.7.0
- Force cobertura to latest 2.7
> Attempting to get travis to build with java 9

- .travis.yml
Introduce command line parameter then dependency check can be finished as expected.
before: https://travis-ci.org/spotbugs/spotbugs-maven-plugin/builds/361014420
after: https://travis-ci.org/spotbugs/spotbugs-maven-plugin/builds/363687083
refs: https://github.com/jeremylong/DependencyCheck/issues/1070#issuecomment-358981169
> Stabilize build on spotbugs branch

- .travis.yml
This fix is same with following change:
https://github.com/spotbugs/spotbugs/commit/59118d93eca8a6c3b44834e0bac257e38abf6dae
> refs #40: stop using absolute path for local_dir

- pom.xml
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
We already require maven 3.1.1 but still had maven core 3.0.0.
> Cleanup build items and stabalize build on maven 3.1.1

- pom.xml
scm has been released with upgrade to allow 4.x api.  scm is only on jdk 7 so forcing it to latest which was previously tested working well.  Locally I get a nice speed boost so hoping for same on travis.
> Scm 1.10.0 and jgit 4.11 upgrade

- pom.xml
jdk11 support is closer here in groovy itself but seems to be an issue still in gmavenplus.
> Downgrade groovy to 2.5.2 and update some more dependencies

- pom.xml
Currently [our site generated by Maven](https://spotbugs.github.io/spotbugs-maven-plugin/) uses @hazendaz's name as copyright holder of this project, because [our site skin uses `<organization>` info in `pom.xml`](https://github.com/apache/maven-skins/blob/eb1c0bf6023923def8b5fdd557fa8bc789d513f8/maven-fluido-skin/src/main/resources/META-INF/maven/site-macros.vm#L397-L420) and [the parent project uses his name as organization](https://github.com/hazendaz/base-parent/blob/14977e3ef9ea05395e081a1cafba8cb0f2e5831e/pom.xml#L29-L32).
In my understanding, the copyright holder of this project is @gleclaire, then I propose to add `<organization>` into this `pom.xml` to overwrite config in parent project.
@gleclaire @hazendaz could you review this PR? Thanks in advance! :)
> Proposal to change copyright holder described in maven site

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
In answer to #71 . @Irian81 mentioned a lack of time and resources to push on the task.
I suggest to close #71 and to conitnue working ton this PR.
The code changes are considered to support the changes on the spotbugs core functionality related to spotbugs/spotbugs#694 together with PR spotbugs/spotbugs#903.
> Add new parameter to provide SpotBugs with source paths from Maven

- pom.xml
This reverts commit d79903720010f4710299e8c743b2103b69d3dd5f.
And further gives a round of testing to confirm pull requests don't cause site release.
> Revert "[pom] Add exclusion for dependency-check-plugin on system scope"

- pom.xml
- src/it/change-xml-filename/invoker.properties
- src/it/change-xml-filename/pom.xml
- src/it/change-xml-filename/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsGui.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotbugsViolationCheckMojo.groovy
Fixes #96 
This change adds an extra parameter to the configuration so you can change the file name of the spotbugsXml.xml output file
> Configurable output filename

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
Adding the xml declaration with the effective encoding in outputSpotbugsFile. 
It resolves a problem when the project uses the sourceEncoding diferent of UTF-8 (e.g: CP1252) which can cause error **MalformedByteSequenceException: Byte inválido 2 da sequência UTF-8 do byte 3**.
> Adding the xml declaration with the effective encoding in outputSpotbugsFile

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
On newer Java versions the following log statement triggers illegal reflective operation warnings:
log.debug("  Plugin Artifacts to be added -> ${pluginArtifacts.toString()}")
Since this is debug logging, the illegal operation can be prevented most of the time by only executing the operation when debug logging is enabled.
Related to: https://github.com/spotbugs/spotbugs-maven-plugin/issues/132
> Tune logging to prevent illegal reflective operation warnings

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
Fixes final issues with xml output on file as requested per multiple tickets and resolved in PR for linux but needed a bit extra for windows + a fix to casing.
> [fix] cp1252 is invalid, use 'windows-1252' instead

- src/it/MFINDBUGS-145/pom.xml
For jdk 14 and above, doxia needs upgraded to work.  This seemed to come and go as jdk 14 was going through updates.  It is now in rampdown and latest openjdk which is listed as oracle and probably close to last build now fails again and can be confirmed on both linux and windows.  While jdk 15 still passes, it is more likely due to that not being jdk 15 really other than adjustments to overall product to indicate such.  In otherwords, it is unlikley to have the hard requirements of jdk 14 still for the most part.
> [fix] MFINDBUGS-145 needs site plugin 3.6 but needs doxia upgraded

- pom.xml
Fixes Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils
https://issues.apache.org/jira/browse/GROOVY-9395
Changelog: https://www.groovy-lang.org/changelogs/changelog-3.0.1.html
> Update Groovy to 3.0.1

- pom.xml
Will allow users a longer time with older maven versions but dropping support for versions prior to 3.2.5.
> Raise maven requirement to 3.2.5

- pom.xml
We require at least jdk 8 to use spotbugs so there is no reason we are still supporting groovy java 6 style usage when we should be using invoke dynamic across the board.
> Move to full groovy indy including our code (invoke dynamic)

- pom.xml
see https://groovy-lang.org/releasenotes/groovy-3.0.html due to incorrectly upgrading too soon.  While testng showed 7.2.0 released, they have also since retrated the release so it was likely a problem in my opinion.
> [pom] Exclude groovy testng as we do not use it

- src/it/check-fail/verify.groovy
- src/it/check-failThreshold/invoker.properties
- src/it/check-failThreshold/pom.xml
- src/it/check-failThreshold/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotbugsViolationCheckMojo.groovy
Resolves #219
Notes:
- First I cleaned up the duplicate parsing of `outputFile` and the scoping of `bugCount` and `errorCount` (see first commit)
- The recent Groovy update from 3.0.3 to 3.0.4 kills your builds: https://travis-ci.org/github/spotbugs/spotbugs-maven-plugin/builds/690024559
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.2.1:install (prepare-integration-test) on project spotbugs-maven-plugin: Execution prepare-integration-test of goal org.apache.maven.plugins:maven-invoker-plugin:3.2.1:install failed: Plugin org.apache.maven.plugins:maven-invoker-plugin:3.2.1 or one of its dependencies could not be resolved: Could not find artifact org.testng:testng:jar:7.2.0 in google-maven-central …
```
> CheckMojo: introduce failThreshold

- src/main/groovy/org/codehaus/mojo/spotbugs/ResourceHelper.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsInfo.groovy
THis helps loading artifacts under Windows, where separator is not '/' , Fixes #34
> Use file api for reading parsing artifact names, Fix #34

- src/it/check-failThreshold/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotbugsViolationCheckMojo.groovy
The differentiated logging I introduced in #222 is actually a bit overzealous for bugs that are below the threshold.
That warning should be info instead and this is what this PR is changing.
> CheckMojo: reduce log to info when bug below threshold

- src/it/check-multi-filter-dups/invoker.properties
- src/it/check-multi-filter-dups/module1/pom.xml
- src/it/check-multi-filter-dups/module2/pom.xml
- src/it/check-multi-filter-dups/pom.xml
- src/it/check-multi-filter-dups/src/main/config/spotbugs-exclude-filters.xml
- src/it/check-multi-filter-dups/verify.groovy
Related to #281 
An IT test has been created to cause and detect the issue. This test checks the existence of the excludeFiltersFile provided on the parent POM in each submodule, when a `relativePath` is used to declare it, taken the specific case from the info and examples provided in #281.
> Add IT test to check excludeFiltersFile duplications on multi-module projects

- .github/workflows/sonar.yaml
- .github/workflows/sonatype.yaml
- .travis.yml
Will eventually drop travis entirely once all pieces are up to date.
> [travis] Drop jdk 16, 15, and 8 as these are done in actions now

- src/main/groovy/org/codehaus/mojo/spotbugs/ResourceHelper.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsInfo.groovy
Original problem was C_ in target directory looking out of place.  The change in #238 caused it to copy all resources into exact locations which under certain setup would cause source path to incorrectly be changed.  After an integration test was added to confirm this, the logic was reverted here and subsequent change to handle windows in additional to linux.  Now no more nested still but the add on jars like fb-contrib are copied into target.  A separate ticket has been opened to address that as that seems wrong.  All other copies seem appropriate.
> Revert fix #238 and correctly handle windows as it was only handling linux type line endings

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
Hi,
fixes #306 
I found that there was an inconsistency between [spotbugs source code](https://github.com/spotbugs/spotbugs/blob/a6f9acb2932b54f5b70ea8bc206afb552321a222/spotbugs/src/main/java/edu/umd/cs/findbugs/FindBugs2.java#L102) and [spotbugs-maven-plugin source code](https://github.com/spotbugs/spotbugs-maven-plugin/blob/spotbugs/src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy#L1065). 
If spotbugs-maven-plugin wants to turn on Spotbugs debugging, the key of the system property is supposed to be set as 'findbugs.debug' instead of 'spotbugs.debug' as shown in the spotbugs source code.
[after-modified.log](https://github.com/spotbugs/spotbugs-maven-plugin/files/6168886/after-modified.log)
[before-modified.log](https://github.com/spotbugs/spotbugs-maven-plugin/files/616888 …
> Fix #306, correctly prints a trace of classes analyzed to standard output.

- src/it/systemPropertyVariables/invoker.properties
- src/it/systemPropertyVariables/pom.xml
- src/it/systemPropertyVariables/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
Some SpotBugs plugins such as FindSecBugs take their options using
system properties. These system properties can be set either before
calling Maven (as environmental variables) or as the parameter to Maven
(using the -D command line option). However, for many users the best way
is to include these option to pom.xml. This patch makes it possible for
the SpotBugs Maven plugin using configuration parameter
systemPropertyVariables.
> Add configuration parameter systemPropertyVariables

- .gitignore
- pom.xml
- src/it/sarif-1/invoker.properties
- src/it/sarif-1/pom.xml
- src/it/sarif-1/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
This change allow the Maven plugin to export the SARIF format - already supported by SpotBugs- to the build directory.
It reuse the same directory configured to export the XML file.
Add the moment, it can only export XML or SARIF (JSON) not both.
By default the report will be placed in `target/spotbugsSarif.json`.
It can be configure inline with:
`-Dspotbugs.sarifOutput=true`
or with XML configuration.
The key goal is to easily allow the configuration of Github workflow with SARIF upload.
https://docs.github.com/en/code-security/secure-coding/integrating-with-code-scanning/uploading-a-sarif-file-to-github
> Add support for SARIF format

- src/it/sarif-2/invoker.properties
- src/it/sarif-2/pom.xml
- src/it/sarif-2/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SourceFileIndexer.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
Github code scanning required path relative to the root of the repository.
With the new option `spotbugs.sarifFullPath`
```
mvn com.github.spotbugs:spotbugs-maven-plugin:4.3.1-SNAPSHOT:spotbugs -Dspotbugs.sarifOutput=true -Dspotbugs.sarifFullPath=true
```
> SARIF support for Github action : Add the option to transform relative path to complete path

- src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
I've fixed `<goal>` in `META-INF/m2e/lifecycle-mapping-metadata.xml`, however this fix isn't enough to run SpotBugs from m2e. I've installed `3.1.6-SNAPSHOT` in local, and confirmed that its goal is linked with lifecycle:
But even when I clean the Eclipse project, it won't run SpotBugs. At least, I found nothing in in progress bar, and no report founds in `target` directory.
> Fix lifecycle mapping metadata

- README.md
this plugin is limited by speed that groovy gets to market with updates affecting jdk releases, there is nothing we can do about that, note the known considerations.
> Add notes on groovy to help users

- README.md
- src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
By itself, our plugin doesn't run in a phase that Eclipse understands for m2e.  Therefore we need to use m2e-code-quality which appears to further use [m2e-discovery-catalog](https://github.com/takari/m2e-discovery-catalog).  I have added a note to use m2e-code-quality to provision the support.  Further our setup at least aligns now to the mojos we have which matches up to m2e-code-quality.  See [m2e-code-quality](https://github.com/m2e-code-quality/m2e-code-quality) for more details.
> Add verify and spotbugs to m2e setup following m2e code quality plugin and added information on m2e code quality

- pom.xml
- src/it-tools/build-tools/pom.xml
- src/it-tools/prime/pom.xml
- src/it/common.xml
- src/it/skipEmpty/pom.xml
- src/it/systemPropertyVariables/pom.xml
Upon maven common filter changes to stop providing extra dependencies into the build that are not needed, the behaviour of app changed to not provide proper asm when running tests.  This has been retooling to ensure it works properly and for the most part (outside 2 tests) all plugins will be up to date now in the integration tests.
> Retool build depedencies to ensure proper loading

- src/it-tools/build-tools/src/main/resources/baseline/spotbugs-baseline-other.xml
- src/it-tools/build-tools/src/main/resources/baseline/spotbugs-baseline-outputstream.xml
- src/it-tools/build-tools/src/main/resources/baseline/spotbugs-baseline.xml
- src/it/check-bug-file-multi-list/invoker.properties
- src/it/check-bug-file-multi-list/pom.xml
- src/it/check-bug-file-multi-list/verify.groovy
- src/it/check-bug-file-multi/invoker.properties
- src/it/check-bug-file-multi/pom.xml
- src/it/check-bug-file-multi/verify.groovy
- src/it/check-bug-file/invoker.properties
- src/it/check-bug-file/pom.xml
- src/it/check-bug-file/verify.groovy
- src/it/exclude-multi-list/invoker.properties
- src/it/exclude-multi-list/pom.xml
- src/it/exclude-multi-list/verify.groovy
- src/it/include-multi-list/invoker.properties
- src/it/include-multi-list/pom.xml
- src/it/include-multi-list/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
The spotbugs plugin only supports multiple files for bug inclusion, exclusion and baseline definition as comma-separated values in the single properties. This makes it very hard to use multiple sets of files in multi-module projects. One basically ends up with overriding the value in every module.
This patch adds additional list support for `<includeFilterFile>`, `<excludeFilterFile>` and `<excludeBugsFile>` as
```
<includeFilterFiles>
<includeFilterFile>...</includeFilterFile>
<includeFilterFile>...</includeFilterFile>
</includeFilterFiles>
<excludeFilterFiles>
<excludeFilterFile>...</excludeFilterFile>
<excludeFilterFile>...</excludeFilterFile>
</excludeFilterFiles>
<excludeBugsFiles>
<excludeBugsFile>...</excludeBugsFile>
<excludeBugsFile>...</excludeBugsFile>
</excludeBugsFiles>
``` …
> add multi-file support to the maven spotbugs plugin

- .github/dependabot.yml
- pom.xml
For site, groovy 4.0.3 changed from 4.0.2 in that javaparser no longer works how it was setup here.  Moved it so site works again.
For dependabot, add in github actions too.
> Build updates

- src/it/check-bug-only-test-sources/invoker.properties
- src/it/check-bug-only-test-sources/pom.xml
- src/it/check-bug-only-test-sources/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/BaseViolationCheckMojo.groovy
If you use this plugin in a project that only has test sources (source
files in the folder `src/test/`) and no source files in the main folder
(`src/main/`), then it'd not validate the report generated by spotbugs.
Instead it would only log 0 bugs.
Instead of verifying only the folder for class files (main folder), we
also check if there are test class files (only if the option
`includeTests` is enabled). If there are test files, validation of the
report takes place.
Fixes #454
> Validate Spotbugs report even if only test sources exist

- pom.xml
other one is not supported any longer and was from 2014.  This one was way out of date too but is back to support and released in 2022.
The current used one is broken but this one is working.
> [pom] Move to codehaus l10n-maven-plugin 1.0.0

- pom.xml
likely was when parent was still using the fork originally, had it listed two times.  Clarify second by using actual group and artifact like everything else in this, keep project version.  Remove the other one as it was running anyways.
> [pom] Cleanup spotbugs on site

- pom.xml
this will bring a timestamp in jar files that are more natural because matching the current project's release
notice: even with timestamp value inherited from parent, reproducible builds is ok https://github.com/jvm-repo-rebuild/reproducible-central/tree/master/content/com/github/spotbugs
> Reproducible Builds: override timestamp value

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
> Make sarifOutputDirectory and sarifOutputFilename configurable

- pom.xml
currently they are now the same.  To ensure we keep same as we likely release more frequently, just keep overriding it to what we are on.
> [pom] Update invoker plugin to 3.4.0 and update groovy used with it

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
The plugin versions before 4.7.3.1 passed the auxiliary classpath via the standard input, which caused a deadlock during parallel builds with non-forked spotbugs. #488
Although this was fixed by removing the -auxclasspathFromInput, this broke the classpath logic.
The solution is to pass the classpath using a file.
> #549 Pass the auxiliary classpath using the -auxclasspathFromFile agument

- src/it/verify-clean/invoker.properties
- src/it/verify-clean/pom.xml
Test simply runs through clean at end to ensure files not still open.  Using 4.7.3.0, I can repeat the reported issue.  The issue is gone in 4.7.3.1 and likely related to the auxpath issue.
> [tests] Add integration test to check file open issues per #517

- src/it/check-no-missing-classes/invoker.properties
- src/it/check-no-missing-classes/pom.xml
- src/it/check-no-missing-classes/src/main/java/test/App.java
- src/it/check-no-missing-classes/verify.groovy
Test ensures issue with aux path fix in 4.7.3.1 does not resurface.  Confirmed this test will fail with usage of 4.7.3.1 but is fixed now on latest.
> [tests] Add check that we are not missing classes for analysis

- .github/workflows/it-maven-4.0.0.yaml
- pom.xml
In regards to maven 4
- Alpha 5 seems to have regression that was resolve here https://github.com/apache/maven/pull/940
In regards to plexus container default
- Per #589, usage was reported.  This comes from doxia logging api.  After looking, it does not appear doxia logging api directly uses it at all.  Further all I could find on doxia 1 was usage in unit tests.  Its deleted from doxia 2.  So this does to some degree indicate we possibly make more items provided.  But for now, simply removed it out.
> Drop maven 4 to alpha 4 / Exclude plexus container default

- pom.xml
- src/it/onlyAnalyzeFileSource/invoker.properties
- src/it/onlyAnalyzeFileSource/only-analyze.txt
- src/it/onlyAnalyzeFileSource/pom.xml
- src/it/onlyAnalyzeFileSource/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
> Add support to load onlyAnalyze classes/packages from specified file.

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
Current implementation simply reads the file using given path. This may cause file not found issue for multi module maven projects.
Get file path using resourceHelper before reading content.
> Fix support for loading onlyAnalyze classes/packages from specified file to handle maven modules correctly by using resourceHelper.

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
Following the discussion in https://github.com/spotbugs/spotbugs/issues/1361 it looks like it could be useful for the maven plugin to expose the `noClassOk` option, so the analysis only shows a warning message (instead of a hard fail) when it expects compiled `.class` files in a folder but cannot find any.
I tried reproducing the problem and also adding an integration test demonstrating the case where the option would be useful but could not reproduce.
@hazendaz is this change acceptable without a corresponding integrationt test?
> Added support for SpotBugs' noClassOk option

- .github/workflows/it-maven-4.0.0.yaml
Skipped 9 as broken and locked up on github, never tested locally but maven released alpha 10 very quickly after so I suspect that was why.  This one works again.
> [GHA] Bump maven 4 to alpha 10

- src/it/html-report/pom.xml
- src/it/html-report/verify.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
[outputDirectory](https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html#outputDirectory) is not working pretty well when I try to run `mvn spotbugs:spotbugs` command.
I think maybe the htmlTempFile should be use `outputDirectory`.
Can you take a look of my PR, Thank you.
> fix outputDirectory not work at running spotbugs:spotbugs goal

- src/main/groovy/org/codehaus/mojo/spotbugs/SourceFileIndexer.groovy
maven has this deprecated, I've never personally used it, never seen it documented and can only assume it was meant to split scripts out which spotbugs would not look at anyways since those are not compiled class files.  Therefore just deleting it.
> Remove scripts as deprecated and not known to be used.

- pom.xml
need to control as we don't release spotbugs at same frequency and need this to stay up to date to support newer jdks.
> [pom] Move bcel into dependency management

- pom.xml
- src/it-tools/prime/pom.xml
- src/it/common.xml
- src/it/empty/pom.xml
- src/it/multi-build/pom.xml
- src/it/site-brazil/pom.xml
- src/it/skipEmpty/pom.xml
fixes issue reported by @elharo with site:site run.
> Make sure site is on doxia 1

- src/main/groovy/org/codehaus/mojo/spotbugs/BaseViolationCheckMojo.groovy
Remove all items that do not belong in this class.  This part looks only at the results, it does not need the information for the reports.  The runs execute 'spotbugs' typically then verify the results.  If the verify one is used, it doesn't execute spotbugs only checks pre-existing.  In either case, most of this was just duplicated from the original mojo and unnecessary.
Also cleanup exit when report directory does not exist to reduce nesting
> Cleanup base violation check mojo

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsGui.groovy
- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
previously always set value then if it was asked by user it was set again causing unnecessary garbage collection, moved it to be outside of ant in the one class so its used the same now in both places it existed (gui and mojo)
> Cleanup encoding logic to speed it up

- pom.xml
`<postBuildHookScript>` is not a maven goal / phase, but instead the name of a file, whose file extension may be omitted.
The intend is to find verify.groovy
```
[DEBUG] post-build script : no script 'verify --no-transfer-progress' found in directory C:\git\spotbugs-maven-plugin\target\it\exclude
```
Fix regression introduced in #1058.
> fix integration test postBuildHookScript

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
no site reports unless site is actually called to generate.  original logic was removed as maven blocked usage of execute.  this restores the behaviour.
> Add logic to restore doxia 1 processing

- src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy
Fixes #75 
Add helper when compile not ran as suggested on #75
> Resolve issue #75 by adding log when no files found to run on spotbugs

- .mvn/jvm.config
- mvnw.cmd
- Remove tiered compilation as not needed java 11 or better as that is the default
- Remove add opens against java.io, java.lang, and java.util as no longer needed
> Update maven wrapper content
